version: '3,8'

services:
 web:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/app
  depends_on:
   - db
  environment:
   NODE_ENV: development
   DB_HOST: db
   DB_USER: user1
   DB_PASSWORD: 123456
   DB_NAME: mydb

 db:
  image: postgres:15
  environment:
   POSTGRES_USER: user1
   POSTGRES_PASSWORD: 123456
   POSTGRES_DB: mydb
  ports:
   - "5432:5432"
  volumes:
   - pgdata:/var/lib/postgresql/data

 pgadmin:
  image: dpage/pgadmin4
  restart: always
  ports:
   - "5050:80"
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: admin
  depends_on:
   - db

volumes:
  pgdata:
